### ISSUE TITLE
Where are we going from here?

### ISSUE THREAD

**Issue by berarma** [davidyell/TimezoneAwareDateTime#5]
After some talk in IRC I've been told this project along with CakePHP PR cakephp/cakephp#8753 could be all I need to handle timezones efficiently in my projects.

What I think would work best for us is handling 3 different timezones (although some projects could do with just 2 of them). The database timezone (usually UTC), the local timezone, and the user timezone. They should be configurable to adapt to any situation. The local and user timezones need to be dynamically configurable since the same app may be accessed by different organization units by users from changing locations.

An hypothetic case: The organization could have a work unit in country A and accesses data in the timezone of this country while a unit in country B would need to access data in another timezone. A user working in one of these units might move to another location and needs to input/output times in another timezone while internally the timezone is the one for the unit it works for.

Sometimes the local timezone is referred as the app or assets timezone, I've changed the name to imply that it's not a unique timezone for all of the assets and the app.

I think CakePHP should automatically translate between these configurable timezones. These are the conversions and how they could be handled:
- database to local: toPHP().
- local to user: cakephp/cakephp#8753
- user to local: marshal().
- local to database: toDatabase().

Do you think this is possible and convenient? Is it within the reach of this project?

**Comment by davidyell** [comment]
Wow, sorry @berarma I've just found this ticket!

I haven't touched this in quite a while. I was hoping to put some more work into it. I do believe that @birdy247 has done some further work on this topic though.

I consider it abandoned at this point. Although I have this code in a live project, so it does work for my minimal use-case.

Useful as a reference only, or a guide to the technique.

**Comment by berarma** [comment]
No worries. I was trying to use UTC in the database but gave up because I couldn't find good support for seamless timezone translations when using with more than one timezone.
